# Generated by Django 2.2.2 on 2019-06-12 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, null=True, verbose_name='Titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True, verbose_name='Nome completo')),
                ('cidade', models.CharField(max_length=255, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=255, null=True, verbose_name='Bairro')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiva', models.FloatField(verbose_name='Raiva')),
                ('nojo', models.FloatField(verbose_name='Raiva')),
                ('alegria', models.FloatField(verbose_name='Raiva')),
                ('medo', models.FloatField(verbose_name='Raiva')),
                ('tristeza', models.FloatField(verbose_name='Raiva')),
                ('surpresa', models.FloatField(verbose_name='Raiva')),
                ('neutro', models.FloatField(verbose_name='Raiva')),
            ],
            options={
                'unique_together': {('raiva', 'nojo', 'alegria', 'medo', 'tristeza', 'surpresa', 'neutro')},
            },
        ),
    ]
