# Generated by Django 2.2.2 on 2019-06-21 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nome do arquivo')),
                ('imagem', models.FileField(blank=True, null=True, upload_to=main.models.diretorio_arquivos, verbose_name='Arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoPagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True, verbose_name='Nome completo')),
                ('cidade', models.CharField(max_length=255, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=255, null=True, verbose_name='Bairro')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('idade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, null=True, verbose_name='Titulo')),
                ('video_url', models.CharField(max_length=600, null=True, verbose_name='URL Vídeo YouTube')),
                ('arquivos', models.ManyToManyField(through='main.ArquivoPagina', to='main.Arquivo')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiva', models.FloatField(verbose_name='Raiva')),
                ('nojo', models.FloatField(verbose_name='Nojo')),
                ('alegria', models.FloatField(verbose_name='Alegria')),
                ('medo', models.FloatField(verbose_name='Medo')),
                ('tristeza', models.FloatField(verbose_name='Tristeza')),
                ('surpresa', models.FloatField(verbose_name='Surpresa')),
                ('neutro', models.FloatField(verbose_name='Neutro')),
            ],
            options={
                'verbose_name': 'Emoção',
                'verbose_name_plural': 'Emoções',
                'unique_together': {('raiva', 'nojo', 'alegria', 'medo', 'tristeza', 'surpresa', 'neutro')},
            },
        ),
        migrations.CreateModel(
            name='ArquivoPaginaPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Arquivo')),
                ('emocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Emocao')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Participante')),
            ],
        ),
        migrations.AddField(
            model_name='arquivopagina',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pagina'),
        ),
    ]
