# Generated by Django 2.2.2 on 2019-06-22 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaEmocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiva', models.FloatField(verbose_name='Raiva')),
                ('nojo', models.FloatField(verbose_name='Nojo')),
                ('alegria', models.FloatField(verbose_name='Alegria')),
                ('medo', models.FloatField(verbose_name='Medo')),
                ('tristeza', models.FloatField(verbose_name='Tristeza')),
                ('surpresa', models.FloatField(verbose_name='Surpresa')),
                ('neutro', models.FloatField(verbose_name='Neutro')),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Arquivo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='emocao',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='pagina',
            name='arquivos',
            field=models.ManyToManyField(blank=True, through='main.ArquivoPagina', to='main.Arquivo'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='video_url',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='URL Vídeo YouTube'),
        ),
        migrations.DeleteModel(
            name='ArquivoPaginaPessoa',
        ),
        migrations.DeleteModel(
            name='Emocao',
        ),
        migrations.AddField(
            model_name='pessoaemocao',
            name='pagina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Pagina'),
        ),
        migrations.AddField(
            model_name='pessoaemocao',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Participante'),
        ),
    ]
