# Generated by Django 2.2.2 on 2019-06-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emocao',
            name='alegria',
            field=models.FloatField(verbose_name='Alegria'),
        ),
        migrations.AlterField(
            model_name='emocao',
            name='medo',
            field=models.FloatField(verbose_name='Medo'),
        ),
        migrations.AlterField(
            model_name='emocao',
            name='neutro',
            field=models.FloatField(verbose_name='Neutro'),
        ),
        migrations.AlterField(
            model_name='emocao',
            name='nojo',
            field=models.FloatField(verbose_name='Nojo'),
        ),
        migrations.AlterField(
            model_name='emocao',
            name='surpresa',
            field=models.FloatField(verbose_name='Surpresa'),
        ),
        migrations.AlterField(
            model_name='emocao',
            name='tristeza',
            field=models.FloatField(verbose_name='Tristeza'),
        ),
    ]
