# Generated by Django 2.2.2 on 2019-06-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190618_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoPagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Arquivo')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pagina')),
            ],
        ),
        migrations.AddField(
            model_name='pagina',
            name='arquivos',
            field=models.ManyToManyField(blank=True, null=True, through='main.ArquivoPagina', to='main.Arquivo'),
        ),
    ]
