# Generated by Django 2.2.2 on 2019-06-20 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190618_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='arquivos',
            field=models.ManyToManyField(through='main.ArquivoPagina', to='main.Arquivo'),
        ),
        migrations.CreateModel(
            name='ArquivoPaginaPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Arquivo')),
                ('emocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Emocao')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Pessoa')),
            ],
        ),
    ]
